<?php

function esculturas_mapa_menu() {
  $items['mapa'] = array(
    'title' => 'Mapa Interactivo',
    'description' => 'Mapa Interactivo',
    'page callback' => 'esculturas_mapa_page',
    'access callback' => true,
    'type' => MENU_CALLBACK,
  );
  return $items;
}

function esculturas_mapa_theme() {
  $path = drupal_get_path('module', 'esculturas_mapa');

  $base = array(
    'path' => $path . '/theme',
  );

  $themes['esculturas_mapa'] = $base + array(
      'template' => 'esculturas_mapa',
  );

  return $themes;
}

function esculturas_mapa_page() {
  drupal_add_js(drupal_get_path('module', 'esculturas_mapa') . '/js/mapa.js');
  return theme('esculturas_mapa', array(
    'variable1' => 'FFF',
    'variable2' => 'ZZZ',
  ));
}
