<?php

module_load_include('inc', 'services', 'includes/services.runtime');
module_load_include('inc', 'esculturas_webservices', 'resources/esculturas_resource');
module_load_include('inc', 'esculturas_webservices', 'resources/autores_resource');
// Libreria externa para formatear output the JSON en 5.3
//module_load_include('php', 'esculturas_webservices', 'include/nicejson');

/**
 * Implements hook_perm().
 *
 * Reservado para todos los permisos que se necesite implementar en este modulo.
 */
//function esculturas_webservices_permission() {
//  return array(
//    'ew nodes' => array(
//      'title' => t('Titulo del permiso'),
//      'description' => t('Comentario del permiso.'),
//    ),
//  );
//}

/**
 * Implements hook_services_resources().
 *
 * Se agrega tantos *_resource como tipos de endpoints se necesiten para otras
 * cosas como taxonomias, noticias, etc.
 */
function esculturas_webservices_services_resources() {

  $resources = array();
  $resources += ew_esculturas_resource_definition();
  $resources += ew_autores_resource_definition();

  return $resources;
}

function ew_get_href($resource_descriptor) {
  $entity = $resource_descriptor["entity"];
  $id = $resource_descriptor["id"];
  $filters = $resource_descriptor["filters"];
  $page = $resource_descriptor["page"];
  $pagesize = $resource_descriptor["pagesize"];

  if(!isset($entity)) {
    throw new Error('$entity must be provided.');
  }

  global $base_url;
  $api_base_path =  $base_url;
  $api_base_path .= "/". services_get_server_info("endpoint_path", "");

  $href .= $api_base_path;
  $href .= "/".$entity;

  if($id) {
    $href .= "/".$id;
  }

  $query = array();

  if(isset($filters)) {
    foreach ($filters as $filter => $values) {
      if(is_array($values)){
        foreach ($values as $i => $value) {
          $query[]= $filter."[".$i."]=".$value;
        }
      }
      else {
        $query[]= $filter."=".$values;
      }
    }
  }

  if(isset($page)){
    $query[]= "page=".$page;
  }

  if(isset($pagesize)){
    $query[]= "pagesize=".$pagesize;
  }

  if(!empty($query)){
    $href .= "?";
    $href .= implode($query, "&");
  }

  return $href;
}
